### PR TITLE
Add TopSky MSAW and STCA inhibit areas

### PR DESCRIPTION
**Pull request by arthuwu**
## Changelog
- Correct MRVA areas as per real-world references
  - MRVA as displayed on AT3 is different to AIP
  - Some lines have been redrawn to a higher fidelity
- Define TopSky MSAW areas 
  - Approach and departure path exclusion zones are a rough estimate for now, eventually I plan on writing something to plonk in the ICAO standard minima for me
- Define TopSky STCA inhibit areas
- Define TopSky AIW inhibit areas for VHHH and VMMC
  - VHHX is not defined for situational awareness
 
image
image

image
(left - new, right - old)

### CODE REVIEW

**Comment by EightSmart** [comment]
MSAW only shows when tag is hovered over (detailed), is this intended?
image

**Comment by EightSmart** [comment]
What are these yellow boxes that display by default?
image

**Comment by arthuwu** [comment]
> MSAW only shows when tag is hovered over (detailed), is this intended? image

fixed, thanks

**Comment by arthuwu** [comment]
> What are these yellow boxes that display by default? image

(note to self: restart es when adding new files to topsky)
these are the AIW inhibit areas but it's a bit too much hassle to hide it without losing some other feature so I've commented it out for now - a solution could be to disable the TopSky AIW entirely since HKCP has one, and create exclusion zones inside HKCP instead (which is actually more realistic as AT3 does not automatically draw leader lines for AIWs)

**Review by EightSmart — APPROVED** [review]

**Pull request merged**
